// Generated by https://quicktype.io

class ApiError {
  String reason;
  String status;

  ApiError({
    this.reason,
    this.status,
  });

  ApiError.fromJsonMap(Map<String, dynamic> json) {
    reason = json['reason'];
    status = json['status'];
  }
}
