// Generated by https://quicktype.io

class Calculator {
  int id;
  int userId;
  String imageUrl;
  String text;
  DateTime selectedDateTime;

  Calculator({
    this.id,
    this.userId,
    this.imageUrl,
    this.selectedDateTime,
  });

  Calculator.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['user_id'];
    imageUrl = json['image_url'];
    text = json['text'];
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'user_id': userId,
        'image_url': imageUrl,
        'text': text,
      };
}
