// Generated by https://quicktype.io

class Email {
  Details details;
  String email;
  int references;
  String reputation;
  bool suspicious;

  Email({
    this.details,
    this.email,
    this.references,
    this.reputation,
    this.suspicious,
  });

  Email.fromJsonMap(Map<String, dynamic> json) {
    //details = Details.fromJsonMap(json['details']);
    email = json['email'];
    references = json['references'];
    reputation = json['reputation'];
    suspicious = json['suspicious'];
  }
}

class Details {
  bool acceptAll;
  bool blacklisted;
  bool credentialsLeaked;
  bool credentialsLeakedRecent;
  bool dataBreach;
  int daysSinceDomainCreation;
  bool deliverable;
  bool disposable;
  bool dmarcEnforced;
  bool domainExists;
  String domainReputation;
  String firstSeen;
  bool freeProvider;
  String lastSeen;
  bool maliciousActivity;
  bool maliciousActivityRecent;
  bool newDomain;
  List<String> profiles;
  bool spam;
  bool spfStrict;
  bool spoofable;
  bool suspiciousTld;
  bool validMx;

  Details({
    this.acceptAll,
    this.blacklisted,
    this.credentialsLeaked,
    this.credentialsLeakedRecent,
    this.dataBreach,
    this.daysSinceDomainCreation,
    this.deliverable,
    this.disposable,
    this.dmarcEnforced,
    this.domainExists,
    this.domainReputation,
    this.firstSeen,
    this.freeProvider,
    this.lastSeen,
    this.maliciousActivity,
    this.maliciousActivityRecent,
    this.newDomain,
    this.profiles,
    this.spam,
    this.spfStrict,
    this.spoofable,
    this.suspiciousTld,
    this.validMx,
  });

  Details.fromJsonMap(Map<String, dynamic> json) {
    acceptAll = json['acceptAll'];
    blacklisted = json['blacklisted'];
    credentialsLeaked = json['credentialsLeaked'];
    credentialsLeakedRecent = json['credentialsLeakedRecent'];
    dataBreach = json['dataBreach'];
    daysSinceDomainCreation = json['daysSinceDomainCreation'];
    deliverable = json['deliverable'];
    disposable = json['disposable'];
    dmarcEnforced = json['dmarcEnforced'];
    domainExists = json['domainExists'];
    domainReputation = json['domainReputation'];
    firstSeen = json['firstSeen'];
    freeProvider = json['freeProvider'];
    lastSeen = json['lastSeen'];
    maliciousActivity = json['maliciousActivity'];
    maliciousActivityRecent = json['maliciousActivityRecent'];
    newDomain = json['newDomain'];
    // profiles = json['profiles'].cast<List<String>>();
    spam = json['spam'];
    spfStrict = json['spfStrict'];
    spoofable = json['spoofable'];
    suspiciousTld = json['suspiciousTld'];
    validMx = json['validMx'];
  }
}
