// Generated by https://quicktype.io

class Image {
  int id;
  int userId;
  String name;
  String type;
  String url;
  String updatedAt;
  String createdAt;
  String deletedAt;
  String thumbnail;

  Image({
    this.id,
    this.userId,
    this.name,
    this.type,
    this.url,
    this.updatedAt,
    this.createdAt,
    this.deletedAt,
    this.thumbnail,
  });

  Image.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    userId = json['userId'];
    name = json['name'];
    type = json['type'];
    url = json['url'];
    updatedAt = json['updatedAt'];
    createdAt = json['createdAt'];
    deletedAt = json['deletedAt'];
    thumbnail = json['thumbnail'];
  }
}
