// Generated by https://quicktype.io


import 'NullString.dart';

class Login {
  NullString deviceType;
  String username;
  String password;
  NullString firebaseToken;

  Login({
    this.deviceType,
    this.username,
    this.password,
    this.firebaseToken,
  });

  Login.fromJsonMap(Map<String, dynamic> json) {
    deviceType = NullString.fromJsonMap(json['device_type']);
    username = json['username'];
    password = json['password'];
    firebaseToken = NullString.fromJsonMap(json['firebase_token']);
  }

  Map<String, dynamic> toJson() => {
        'username': username,
        'password': password,
        'device_type': deviceType.toJson(),
        'firebase_token': firebaseToken.toJson(),
      };
}
