// Generated by https://quicktype.io

class Streaming {
  int id;
  int clinicId;
  String url;
  String code;

  Streaming({
    this.id,
    this.clinicId,
    this.url,
    this.code,
  });

  Streaming.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    clinicId = json['clinic_id'];
    url = json['url'];
    code = json['code'];
  }

  Map<String, dynamic> toJson() => {
        'id': id,
        'clinic_id': clinicId,
        'image_url': url,
        'code': code,
      };
}

/*
        "id": 1,
        "clinic_id": 10,
        "url": "https://www.youtube.com/watch?v=ioUroK7Dnhg",
        "code": "AAAA",
        "available": 1,
        "updated_at": "2021-01-25T00:00:00Z",
        "created_at": "2021-01-25T00:00:00Z",
        "username": ""
 */
