// Generated by https://quicktype.io

class Success {
  String result;

  Success({
    this.result,
  });

  Success.fromJsonMap(Map<String, dynamic> json) {
    result = json['result'];
  }

  Map<String, dynamic> toJson() => {
        'result': result,
      };
}
