// Generated by https://quicktype.io


import 'NullString.dart';

class User {
  int id;
  String username;
  String password;
  NullString token;
  NullString firebaseToken;
  NullString pushToken;
  NullString deviceType;
  User({
    this.id,
    this.username,
    this.password,
    this.token,
    this.firebaseToken,
    this.pushToken,
    this.deviceType,
  });

  User.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    username = json['username'];
    password = json['password'];
    token = NullString.fromJsonMap(json['token']);
    firebaseToken = NullString.fromJsonMap(json['firebase_token']);
    pushToken = NullString.fromJsonMap(json['push_token']);
    deviceType = NullString.fromJsonMap(json['device_type']);
  }
}
